workflows:
  windows-flutter-build:
    name: Flutter Windows Build
    instance_type: windows_x1

    environment:
      flutter: stable

    scripts:
      - name: Check Flutter version
        script: flutter --version

      - name: Get dependencies
        script: flutter pub get

      - name: Enable Windows desktop
        script: flutter config --enable-windows-desktop

      - name: Build Windows app
        script: flutter build windows

    artifacts:
      - build/windows/runner/Release/**

    publishing:
      email:
        recipients:
          - steven.hany.194@gmail.com
